### ISSUE TITLE
Error: list: failed to list: etcdserver: leader changed

### ISSUE THREAD

**Issue by toxynoid** [vanillastack/vanillastack#10]
Server Version 0.500.08d910d7

TASK [deploy-kubernetes : Deploy latest version of Cilium] *********************
fatal: [master1]: FAILED! => {"changed": false, "command": "/usr/local/bin/helm --namespace=kube-system list --output=yaml --filter cilium", "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: list: failed to list: etcdserver: leader changed\n", "stderr": "Error: list: failed to list: etcdserver: leader changed\n", "stderr_lines": ["Error: list: failed to list: etcdserver: leader changed"], "stdout": "", "stdout_lines": []}

If more information is needed I'll provide it.

**Comment by galexrt** [comment]
Seem like something isn't quite right with the ETCD cluster for some reason.
If you are able to run `kubectl` already, could you check if any `kubectl get nodes`, etc. return anything?

**Comment by toxynoid** [comment]
Sorry, I cannot reproduce. I'm hitting issue #8 this time.

**Comment by christiancloudical** [comment]
Did you validate, switching to more powerful systems is fixxing your issue?

**Comment by toxynoid** [comment]
I have 12 cores HT enabled (24 threads) and 142 GB RAM for this cluster. Workload is low. I can't imagine how more power would help.

**Comment by christiancloudical** [comment]
As you mentioned, hitting #8, that one is closed since 3 hours, because he mentioned, that faster systems solve that issue.
Just wanted to make sure, that is not the issue on your side.

Can you offer a little more information about your environment?
How many systems
OS 
External / Internal Loadbalancer

**Comment by toxynoid** [comment]
- 3 x Master 12GB 2CPU
- 4 x Worker 12GB 2CPU
- 1 x Loadbalancer 8GB 1CPU

All virtual machines running fedora 32 on a fedora 32 host with 12 Cores HT enabled and 142GB.

**Comment by christiancloudical** [comment]
Hey @toxynoid New Year New Luck,
did you try to install again with latest version?
We did a lot of refactoring and Bugfixxing meanwhile, and as we came to a point, some operating systems often make problems, we decided to keep debian as only supported operating system in the next release.

Would be nice if you could switch to debian 10 and keep up testing with us

**Comment by pschl1337** [comment]
Hey @toxynoid, 

since we haven't heard from you for a long time, I think the issue no longer exists? Otherwise you can open the ticket again at any time so that we can find a suitable solution for you together. :)

Greetz
Patrick
