### ISSUE TITLE
Installation fails when trying to deploy Harbor

### ISSUE THREAD

**Issue by jaybe1966** [vanillastack/vanillastack#12]
Trying the installation of release 20.10 with installer version: Server Version 0.500.08d910d7

Trying the following configuration:

```
X Enable Rook Dashboard
X Enable Rook Monitoring
X Install Harbor
- Install Prometheus
- Install Grafana
- Install Elasticsearch
- Install Fluentd
- Install Kibana
- Install Jaeger Tracing
X Install Nginx Ingress
X Install Cert-Manager
X Install Kubernetes Dashboard
```

The installation fails, the pod "harbor-harbor-core" is permanent in status "ContainerCreating"
`harbor-harbor-core-dbf845545-lq76r             0/1     ContainerCreating   0          63m`

Logfile: [2020-10-28_s4.log](https://github.com/vanillastack/vanillastack/files/5451327/2020-10-28_s4.log)

**Comment by kisahm** [comment]
harbor cannot mount the tls secret. 
i'll verify it in my test environment

**Comment by leejjoon** [comment]
I have encountered a similar problem.

For my case, the host value in  'harbor-harbor-ingress' and 'harbor-harbor-ingress-notary' was set to 'harbor.test.vanillastack.cloudical.net' instead of the value I specified, which I believe prevented the creation of the tls secret. Manually correcting these fixed the problem for me.

**Comment by jaybe1966** [comment]
> I have encountered a similar problem.
> 
> For my case, the host value in 'harbor-harbor-ingress' and 'harbor-harbor-ingress-notary' was set to 'harbor.test.vanillastack.cloudical.net' instead of the value I specified, which I believe prevented the creation of the tls secret. Manually correcting these fixed the problem for me.

How to fix this manually?

**Comment by leejjoon** [comment]
During the installation, I simply used "kubectl edit" command to fix the wrong values in the ingress definitions. This is just a workaround to make the installation proceeds, not a solution.

**Comment by kisahm** [comment]
should be fixen in latest image
