### ISSUE TITLE
Configuration of the external load balancer

### ISSUE THREAD

**Issue by lucj** [vanillastack/vanillastack#16]
This is more a question than an issue :)
In the Cluster-Settings step, if I want to provide a load balancer, how does this one should be configured ? Should it pass-through 443 to 6443 on each master nodes ?

<img width="1371" alt="Capture d’écran 2020-12-03 à 10 43 18" src="https://user-images.githubusercontent.com/182406/101140297-0e78ac00-3613-11eb-9902-615d1f7e89f3.png">

**Comment by kisahm** [comment]
You find the information here:
https://docs.vanillastack.io/userguide/20.09/setup/requirements.html#_external_loadbalancer

**Comment by lucj** [comment]
Thanks, this is really helpful.
Could be really interesting to have this link in the Cluster-Settings section of the installer as well.
