### ISSUE TITLE
Error on deploy-keycloak task

### ISSUE THREAD

**Issue by lucj** [vanillastack/vanillastack#17]
Hello,

The stack installation went fine (the cluster is available) but I got an error message regarding the deploy-keycloak task:

````
TASK [deploy-keycloak : generate bearertoken] **********************************
FAILED - RETRYING: generate bearertoken (120 retries left).
...
FAILED - RETRYING: generate bearertoken (2 retries left).
FAILED - RETRYING: generate bearertoken (1 retries left).
fatal: [master1]: FAILED! => {"attempts": 120, "changed": false, "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "https://keycloak.vanilla.techwhale.io/auth/realms/master/protocol/openid-connect/token"}
````

I have a load balancer in front of the master nodes only (as I cannot use the same LB for both workers and masters).
I did not find the exact configuration in the documentation, could you confirm that admin.cluster.domain and keycloak.cluster.domain should be configured to reach a worker node ?

**Comment by kisahm** [comment]
Hi @lucj,

all domains (like keycloak, grafana, etc) should point to the loadbalanacer (internal/external) ip.
the LB balance the traffic to the ingress node ports.

**Comment by lucj** [comment]
Thanks @kisahm, there is surely something I've done incorrectly then but cannot figure out what this is.

The error:
````
fatal: [master1]: FAILED! => {"attempts": 120, "changed": false, "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 0] Error>", "redirected": false, "status": -1, "url": "https://keycloak.vanilla.techwhale.io/auth/realms/master/protocol/openid-connect/token"}
````

seems to be due to the fact cert manager is not able to reach the ingress controller Pod.

Logs of cert manager:
````
E0104 09:21:52.577867       1 sync.go:182] cert-manager/controller/challenges "msg"="propagation check failed" "error"="wrong status code '503', expected '200'" "dnsName"="keycloak.vanilla.techwhale.io" "resource_kind"="Challenge" "resource_name"="keycloak-tls-pbbp8-3677282599-3819040120" "resource_namespace"="keycloak" "resource_version"="v1" "type"="HTTP-01"
````

The load balancer exposing the workers is configured with the following:

<img width="618" alt="Capture d’écran 2021-01-04 à 10 27 22" src="https://user-images.githubusercontent.com/182406/103520509-8edf3680-4e77-11eb-86a8-4a1c9b136168.png">

Each worker node appears to be down from the LB point of view, even if each worker returns a 200 on 
````
curl http://IP:30080/healthz
````
Any idea what could be the problem ?

**Comment by lucj** [comment]
Digging a little bit deeper, it seems the load balancer tries to reach the worker nodes using their private IPs (all workers are in a same DigitalOcean VPC) but this does not work.

For instance I can reach the ingress controller sending a request from worker1 to worker2 using worker2's external IP.

```
root@worker1:~# curl -I WORKER_2_EXTERNAL_IP:30080/healthz
HTTP/1.1 200 OK
Date: Mon, 04 Jan 2021 14:03:55 GMT
Content-Type: text/html
Content-Length: 0
Connection: keep-alive
```

But I cannot reach the ingress controller sending a request from worker1 to worker2 using worker2's internal IP (event if there are in the same VPC):

```
root@worker1:~# curl -I WORKER_2_INTERNAL_IP:30080/healthz
curl: (7) Failed to connect to 10.131.0.6 port 30080: Connection refused
```

From worker1 I, can ping worker2 using its internal IP though:
```
root@worker1:~# ping -c3 10.131.0.6
PING 10.131.0.6 (10.131.0.6) 56(84) bytes of data.
64 bytes from 10.131.0.6: icmp_seq=1 ttl=64 time=1.79 ms
64 bytes from 10.131.0.6: icmp_seq=2 ttl=64 time=0.548 ms
64 bytes from 10.131.0.6: icmp_seq=3 ttl=64 time=0.538 ms

--- 10.131.0.6 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2029ms
rtt min/avg/max/mdev = 0.538/0.958/1.789/0.587 ms
```

Any idea why the NodePort is not reachable when using the internal IP ?

**Comment by kisahm** [comment]
coud you check how the port binding looks like on the node?

```lsof -i :30080
lsof -i :30443```
