### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by fabriziopicconi** [vanillastack/vanillastack#18]
Hi I'm trying to install minimal (non HA-Installation 1master+ 3worker) staging (non-production) platform.
Click on "Install" @summary page I get this error.
TypeError: Cannot read property 'keystone' of undefined
    at /usr/workdir/src/routes/api/setup.js:560:41
    at Layer.handle [as handle_request] (/usr/workdir/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/workdir/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/workdir/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/workdir/node_modules/express/lib/router/layer.js:95:5)
    at /usr/workdir/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/workdir/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/workdir/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/workdir/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/workdir/node_modules/express/lib/router/index.js:47:12)

here the Request body in the POST:
{"isHA":false,"general":{"installRook":true,"installCF":false,"installOS":true,"harborUser":"","harborKey":""},"nodes":[{"host":"192.168.9.141","user":"root","role":"M","labels":[]},{"host":"192.168.9.28","user":"root","role":"W","labels":["rook","os"]},{"host":"192.168.9.240","user":"root","role":"W","labels":["rook","os"]},{"host":"192.168.9.129","user":"root","role":"W","labels":["rook","os"]}],"cluster":{"ip":"192.168.9.254","fqdn":"test.domain","pod_cidr":"10.0.0.0/8","service_cidr":"10.96.0.0/12","usefqdn":true,"adminfqdn":"admin","useadminfqdn":true,"useExternalLb":false},"rook":{"dashboard":false,"monitoring":true,"replicaLevel":3},"openstack":{"domain":"openstack.test.domain","release":"stein","tls":true,"mariadb":true,"mariadb_size":30,"rabbitmq":true,"rabbitmq_size":30,"barbican":true,"barbican_endpoint":"barbican","cinder_endpoint":"cinder","cinder":true,"cinder_backend":"ceph","cinder_backup":false,"glance_endpoint":"glance","glance":true,"glance_backend":"ceph","heat_endpoint":"heat","heat":true,"horizon_endpoint":"horizon","horizon":true,"keystone_endpoint":"keystone","keystone":true,"mistral_endpoint":"mistral","mistral":true,"neutron":true,"neutron_endpoint":"neutron","neutron_interface_tunnel":"eth1","neutron_interface_external":"eth2","neutron_l3ha":false,"neutron_overlayNetworkType":"VXLAN","neutron_maxAgentsPerRouter":2,"neutron_dhcpAgents":2,"nova_cpuMode":"host-model","nova_virtType":"Kvm","nova_placement_endpoint":"placement","nova_novnc_endpoint":"novnc","nova":true,"nova_endpoint":"nova","senlin_endpoint":"senlin","senlin":false},"cf":{"fqdn":"cf","stratos":false,"stratos_endpoint":"stratos"},"additional":{"harbor":true,"prometheus":true,"grafana":true,"elastic":false,"fluentd":false,"kibana":false,"dashboard":true,"certmgr":true,"nginx":true,"jaeger":false,"polyverse":{"enable":false,"key":""}},"letsencrypt":{"issuer":"letsencrypt-staging","issuerEmail":"me@test.domain"},"uuid":"90ccdabc-11b0-4c49-9951-ec98b1092f3f","dry":false}

**Comment by j0x00** [comment]
I'll check that. We are currently working on vars, maybe keystone slipped through. I'll get back to you @fabriziopicconi as soon as I reviewed the issue

**Comment by fabriziopicconi** [comment]
Thank you, I'm waiting for your news,

**Comment by houshym** [comment]
same error in my case:
1- 1 master and 3 workers node

**Comment by j0x00** [comment]
@houshym yeah I already found the issue and it will be solved with the next merge/release. We are currently working on vars in our deployment scripts and there is a miss match with what the container expects. I hope this issue is fixed till next week

**Comment by ZonD80** [comment]
Confirm. Installation is broken.

**Comment by j0x00** [comment]
@ZonD80 the bug is already solved internally. When all checks are passed a new release will be issued.

**Comment by ZonD80** [comment]
Thank you! FYI live cd is not working as well. Anyway, waiting for push. Have a nice day!

**Comment by j0x00** [comment]
@ZonD80 thanks for the info. The Docker image is the base for the live iso, this is why it is not working as well.

We have now merged the issue and a now image version is available 
`docker run --name vanilla -p 8080:8080 --rm harbor.vanillastack.io/vanillastack/installer:latest` 
Please try your setup again and if you encounter any issues, use the new installer repo [vanillastack-installer](https://github.com/vanillastack/vanillastack-installer)

thank you everyone for your patients. I'll close this issue as it is solved with vanillastack/vanillastack-installer@323e9b7

**Comment by houshym** [comment]
POST /api/v1/setup 500 9.117 ms - 1130
TypeError: Cannot read property 'keystone' of undefined
    at /usr/workdir/src/routes/api/setup.js:560:41
    at Layer.handle [as handle_request] (/usr/workdir/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/workdir/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/workdir/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/workdir/node_modules/express/lib/router/layer.js:95:5)
    at /usr/workdir/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/workdir/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/workdir/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/workdir/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/workdir/node_modules/express/lib/router/index.js:47:12)
825587572 Setup started

**Comment by j0x00** [comment]
@houshym have you made sure to delete any previous vanillastack docker images and pulled the new one?

**Comment by houshym** [comment]
checking now. is there any slack channel?

**Comment by houshym** [comment]
checking with the new image and VanillaStack installation failed following is log

PLAY [create inventory for scaling] ********************************************
[WARNING]: While constructing a mapping from
/tmp/ansible/e0285f32-1690-4b5a-9654-9b97820ea164/group_vars/all/global.yaml,
line 233, column 3, found a duplicate dict key (replicas). Using last defined
value only.

TASK [Gathering Facts] *********************************************************
ok: [vagrant]

TASK [deploy-kubernetes : 00_create_new_inventory] *****************************
included: /tmp/ansible/roles/deploy-kubernetes/tasks/00_create_new_inventory.yaml for vagrant

TASK [deploy-kubernetes : get nodes in cluster] ********************************
fatal: [vagrant]: FAILED! => {"changed": false, "cmd": "kubectl get nodes -o name", "msg": "[Errno 2] No such file or directory: b'kubectl': b'kubectl'", "rc": 2}
...ignoring

TASK [deploy-kubernetes : Add all hosts running this playbook to the done group] ***
ok: [vagrant] => (item=vagrant)

TASK [deploy-kubernetes : Add all hosts running this playbook to the done group] ***
ok: [vagrant] => (item=vagrant)

PLAY [Wait for nodes] **********************************************************

TASK [wait-for-nodes : Wait for nodes to be ready] *****************************
ok: [vagrant]

PLAY [Secure Servers (Installing Polyverse)] ***********************************

TASK [Gathering Facts] *********************************************************
ok: [vagrant]

TASK [deploy-polyverse : Upgrade all packages to the latest version] ***********
skipping: [vagrant]

TASK [deploy-polyverse : Install Polyverse Repos] ******************************
skipping: [vagrant]

TASK [deploy-polyverse : Reinstall polymorphed packages on Debian and restart Server] ***
skipping: [vagrant]

TASK [deploy-polyverse : Reinstall polymorphed packages on Centos and restart Server] ***
skipping: [vagrant]

TASK [deploy-polyverse : Reboot machine to get latest updates] *****************
skipping: [vagrant]

PLAY [Configure Servers] *******************************************************

TASK [Gathering Facts] *********************************************************
ok: [vagrant]

TASK [deploy-kubernetes : 01_configure_systems] ********************************
included: /tmp/ansible/roles/deploy-kubernetes/tasks/01_configure_systems.yaml for vagrant

TASK [deploy-kubernetes : Check if distribution is supported] ******************
fatal: [vagrant]: FAILED! => {"changed": false, "msg": "This disribution is currently not supported by VanillaStack"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
vagrant                    : ok=9    changed=0    unreachable=0    failed=1    skipped=5    rescued=0    ignored=1   

-1

**Comment by houshym** [comment]
is it mandatory using debian10? I am using ubuntu 20.4

**Comment by j0x00** [comment]
@houshym as far as I know there is no slack channel currently, but you can issue requests on our [community board](https://discourse.vanillastack.io/). As for now I would recomment asking those questions in a new issue, because I am working on the backend and cannot really clarify issues within ansible deployments

**Comment by houshym** [comment]
can we run vanillastack (pure dev env for demo ) with all component including openstack on 4 machine( 1 master 4GB and 2 core and 3worker node 4GB and 2 core)?

**Comment by j0x00** [comment]
@houshym I strongly recommend to ask those kind of questions in the above mentioned community board.
