### ISSUE TITLE
unable to pull installer using docker

### ISSUE THREAD

**Issue by czadikem** [vanillastack/vanillastack#19]
I am unable to do `docker pull harbor.vanillastack.io/vanillastack/installer`  as I get
`Using default tag: latest
Error response from daemon: received unexpected HTTP status: 503 Service Temporarily Unavailable`
How can I pull the image?

**Comment by trickert76** [comment]
Also, the dockumentation on https://docs.vanillastack.io/userguide/21.01/setup/installer.html says concrete

    docker pull harbor.vanillastack.io/VanillaStack/installer:latest

Which is also wrong and docker quits with

    invalid reference format: repository name must be lowercase

**Comment by volkermauel** [comment]
Running into the same problem

**Comment by MiningPickaxe** [comment]
Still hasn't been fixed yet, was this project abandoned by Cloudical?

**Comment by czadikem** [comment]
I gave up on it instead I would use Harvestor, Fedora Server, Fedora CoreOS, or K3s server.  As it actually works and provides kubernetes easily.
