### ISSUE TITLE
State of repo and contributions

### ISSUE THREAD

**Issue by funnym0nk3y** [vanillastack/vanillastack#2]
What is the state of this repo compared to the website? There are some projects listed, which to my knowledge are not yet included in this repo (Istio, Keycloak, etc.). I guess they will be included eventually, but what's the state on them and are you accepting contributions in this early state?

**Comment by kisahm** [comment]
currently we are structuring the project to open it for "external" contributors. 
the process will be described in the next days. 

in the mean time: feel free to open issues in regards of bugs and feature requests.

**Comment by IvoMende** [comment]
We released an updated version in Aug2022. Feel free to open a new ticket as soon as you had time to check.
