### ISSUE TITLE
after click on "install" all remains quite (no status / progress shown in the browser)

### ISSUE THREAD

**Issue by chrismade** [vanillastack/vanillastack#21]
in the after booting into the Vanilla Install 20.11 VM the start screen appears as expected - all config step can be done as expected up to the "summary" - however, clicking "install" just show "installing" without showing any status and progress 

I can't see any user error or config here because the VM is turn-key like  - everything is already pre-set - so I doubt any user settings can create or change the situation.

there is an easy workaround and use the installer despite of this issue:
press <F11> to leave full screen, click on left-most vanilla at the buttom, from this menue click "system Tools" > "LXTerminal"
in this terminal enter

```
docker exec -it vanilla-installa /bin/sh
cd /root
```

find the ansible.log 
here which is supposed to appear in the browser (like in the YouTube videos)

**Comment by pschl1337** [comment]
Hey chrismade, 

thanks for your report :)
As i mentioned in the other issue report, the problem should be fixed now. Please notice, the new vanillastack will be available soon, including the newest versions of the used tools and we have already fixed the dirty pipe bug in the linux kernel. 

https://linuxiac.com/linux-kernel-vulnerability-dirty-pipe/#:~:text=CVE%2D2022%2D0847%2C%20aka,the%20only%20ones%20at%20risk.

Have a great day and we are looking forward to your response :)

Greetz 
Patrick

**Comment by IvoMende** [comment]
I close this ticket due to new version release. Please open a new one if you had time to check.
