### ISSUE TITLE
Failed to connect to repo.vanillastack.cloudical.net port 443

### ISSUE THREAD

**Issue by schadom** [vanillastack/vanillastack#22]
Hi,

unfortunately the repo seems to be currently offline, thus installation fails:

	TASK [deploy-kubernetes : Add key for cri-o repos] *****************************
	FAILED - RETRYING: Add key for cri-o repos (3 retries left).
	FAILED - RETRYING: Add key for cri-o repos (3 retries left).
	FAILED - RETRYING: Add key for cri-o repos (3 retries left).
	FAILED - RETRYING: Add key for cri-o repos (3 retries left).
	FAILED - RETRYING: Add key for cri-o repos (3 retries left).
	FAILED - RETRYING: Add key for cri-o repos (3 retries left).
	FAILED - RETRYING: Add key for cri-o repos (2 retries left).
	FAILED - RETRYING: Add key for cri-o repos (2 retries left).
	FAILED - RETRYING: Add key for cri-o repos (2 retries left).
	FAILED - RETRYING: Add key for cri-o repos (2 retries left).
	FAILED - RETRYING: Add key for cri-o repos (2 retries left).
	FAILED - RETRYING: Add key for cri-o repos (2 retries left).
	FAILED - RETRYING: Add key for cri-o repos (1 retries left).
	FAILED - RETRYING: Add key for cri-o repos (1 retries left).
	FAILED - RETRYING: Add key for cri-o repos (1 retries left).
	FAILED - RETRYING: Add key for cri-o repos (1 retries left).
	FAILED - RETRYING: Add key for cri-o repos (1 retries left).
	FAILED - RETRYING: Add key for cri-o repos (1 retries left).
	failed: [control03] (item=https://repo.vanillastack.cloudical.net/public-gpg-key) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": "https://repo.vanillastack.cloudical.net/public-gpg-key", "msg": "Failed to download key at https://repo.vanillastack.cloudical.net/public-gpg-key: Request failed: <urlopen error timed out>"}
	failed: [compute03] (item=https://repo.vanillastack.cloudical.net/public-gpg-key) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": "https://repo.vanillastack.cloudical.net/public-gpg-key", "msg": "Failed to download key at https://repo.vanillastack.cloudical.net/public-gpg-key: Request failed: <urlopen error timed out>"}
	failed: [control01] (item=https://repo.vanillastack.cloudical.net/public-gpg-key) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": "https://repo.vanillastack.cloudical.net/public-gpg-key", "msg": "Failed to download key at https://repo.vanillastack.cloudical.net/public-gpg-key: Request failed: <urlopen error timed out>"}
	failed: [compute01] (item=https://repo.vanillastack.cloudical.net/public-gpg-key) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": "https://repo.vanillastack.cloudical.net/public-gpg-key", "msg": "Failed to download key at https://repo.vanillastack.cloudical.net/public-gpg-key: Request failed: <urlopen error timed out>"}
	failed: [compute02] (item=https://repo.vanillastack.cloudical.net/public-gpg-key) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": "https://repo.vanillastack.cloudical.net/public-gpg-key", "msg": "Failed to download key at https://repo.vanillastack.cloudical.net/public-gpg-key: Request failed: <urlopen error timed out>"}
	failed: [control02] (item=https://repo.vanillastack.cloudical.net/public-gpg-key) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": "https://repo.vanillastack.cloudical.net/public-gpg-key", "msg": "Failed to download key at https://repo.vanillastack.cloudical.net/public-gpg-key: Request failed: <urlopen error timed out>"}

From another location with curl:

	➜  ~ curl -Ik https://repo.vanillastack.cloudical.net/public-gpg-key
	curl: (28) Failed to connect to repo.vanillastack.cloudical.net port 443 after 75010 ms: Operation timed out

Regards

**Comment by PeeK1e** [comment]
We'll be trying to release a new version next week, the current repositories in the playbook seem outdated.

**Comment by PeeK1e** [comment]
Hi,
we have released a new version of Vanillastack see
https://github.com/vanillastack/vanillastack/tree/v2.0.0

**Comment by IvoMende** [comment]
Closed due to new version release... 
Please open a new ticket as soon you had time to check out.
