### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by schadom** [vanillastack/vanillastack#23]
As the title says. Thanks

**Comment by PeeK1e** [comment]
Hi sorry for the late reply, yes this project is still alive were working on releasing a new version soon :)

**Comment by ardantus** [comment]
install using docker error repo, install using ansible error in helm.

**Comment by ardantus** [comment]
failed: [master-2] (item=https://repo.vanillastack.cloudical.net/public-gpg-key) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": "https://repo.vanillastack.cloudical.net/public-gpg-key", "msg": "Failed to download key at https://repo.vanillastack.cloudical.net/public-gpg-key: Request failed: <urlopen error timed out>"}

**Comment by PeeK1e** [comment]
Well be trying to release a new version next week, the current repositories in the playbook seem outdated.

**Comment by PeeK1e** [comment]
@ardantus We have released a new version of Vanillastack v2.0.0
If you encounter any problems feel free to open another issue
