### ISSUE TITLE
Error writing Crisocket information for the control-plane node

### ISSUE THREAD

**Issue by jaybe1966** [vanillastack/vanillastack#5]
When trying to install vanillastack with the docker image
harbor.cloudical.net/vanillastack/installer:latest              5af4467948f2
I receive the following error:
Error writing Crisocket information for the control-plane node: timed out waiting for the condition
[2020-10-02_Installation.log](https://github.com/vanillastack/vanillastack/files/5321326/2020-10-02_Installation.log)

Maybe the nodes are coming up too slow, so timeout is too low. They are all VirtualBox Installations on an older system.

**Comment by galexrt** [comment]
@jaybe1966 Could you check on the VMs if the `crio` service is running? It should but maybe there is an issue, which needs to considered during installation.

```
systemctl status crio
```

Please post the logs of the `crio` service as well:
```
journalctl --no-pager -u crio
```

**Comment by spyfly** [comment]
> @jaybe1966 Could you check on the VMs if the `crio` service is running? It should but maybe there is an issue, which needs to considered during installation.
> 
> ```
> systemctl status crio
> ```
> 
> Please post the logs of the `crio` service as well:
> 
> ```
> journalctl --no-pager -u crio
> ```
My install has failed with the same issue, install log can be found [here](https://gist.github.com/spyfly/1cedef9b1a2f1aa4741da9cbead90f2c)


`crio` seems to be running on the master and all three worker nodes.


And here are the crio service logs: 
- [Master](https://gist.github.com/spyfly/6b4c71e99bbbb01974489dfddfea11da)
- [Worker1](https://gist.github.com/spyfly/32d2954aebc5068361d5486ea93e7be0)
- [Worker2](https://gist.github.com/spyfly/d48c38df2ea5412e09b6eee2c0f713f7)
- [Worker3](https://gist.github.com/spyfly/f6930b5b1ff53b431724025eba03ab35)

**Comment by kisahm** [comment]
@jaybe1966 which linux distribution are you using?

**Comment by spyfly** [comment]
> @jaybe1966 which linux distribution are you using?

I'm not @jaybe1966, but I'm running Fedora 32 Server

**Comment by jaybe1966** [comment]
> @jaybe1966 which linux distribution are you using?

Running Fedora 32 Server on the nodes.
Installer is running in a docker container on Linux Mint Debian Edition.

**Comment by kisahm** [comment]
could you test the new installer images
we've fixed a lot of crio, cilium and os basic stuff.

new (latest) docker image: harbor.cloudical.net/vanillastack/installer:0.500.4dd79119

**Comment by jaybe1966** [comment]
With image harbor.cloudical.net/vanillastack/installer:0.500.4dd79119 I get the following error:

fatal: [system141]: FAILED! => {"msg": "The conditional check 'polyverse.enabled' failed. The error was: error while evaluating conditional (polyverse.enabled): 'polyverse' is undefined\n\nThe error appears to be in '/tmp/ansible/roles/deploy-polyverse/tasks/main.yaml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Upgrade all packages to the latest version\n  ^ here\n"}
fatal: [system142]: FAILED! => {"msg": "The conditional check 'polyverse.enabled' failed. The error was: error while evaluating conditional (polyverse.enabled): 'polyverse' is undefined\n\nThe error appears to be in '/tmp/ansible/roles/deploy-polyverse/tasks/main.yaml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Upgrade all packages to the latest version\n  ^ here\n"}
fatal: [system143]: FAILED! => {"msg": "The conditional check 'polyverse.enabled' failed. The error was: error while evaluating conditional (polyverse.enabled): 'polyverse' is undefined\n\nThe error appears to be in '/tmp/ansible/roles/deploy-polyverse/tasks/main.yaml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Upgrade all packages to the latest version\n  ^ here\n"}
fatal: [system144]: FAILED! => {"msg": "The conditional check 'polyverse.enabled' failed. The error was: error while evaluating conditional (polyverse.enabled): 'polyverse' is undefined\n\nThe error appears to be in '/tmp/ansible/roles/deploy-polyverse/tasks/main.yaml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Upgrade all packages to the latest version\n  ^ here\n"}
fatal: [system145]: FAILED! => {"msg": "The conditional check 'polyverse.enabled' failed. The error was: error while evaluating conditional (polyverse.enabled): 'polyverse' is undefined\n\nThe error appears to be in '/tmp/ansible/roles/deploy-polyverse/tasks/main.yaml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Upgrade all packages to the latest version\n  ^ here\n"}
fatal: [system146]: FAILED! => {"msg": "The conditional check 'polyverse.enabled' failed. The error was: error while evaluating conditional (polyverse.enabled): 'polyverse' is undefined\n\nThe error appears to be in '/tmp/ansible/roles/deploy-polyverse/tasks/main.yaml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Upgrade all packages to the latest version\n  ^ here\n"}

**Comment by jaybe1966** [comment]
tested with the new image
