### ISSUE TITLE
debian10 installation fails.

### ISSUE THREAD

**Issue by chymian** [vanillastack/vanillastack#6]
installer: selfcreated from git
deploy VM: fed32
masters: 3 VMs, debian 10
nodes: 3VMs, debian 10
SW-selection: all deselected, habour: with and without, same result

## description
to make the pip-install work, the prerequisites have to be fulfilled.
the install-process fails while it tries to deploy habour (even if deselected).
see log below.
that was done yesterday, before the merger of testing into master.
with the today git, it fails with a polyverse.enabled condition.

Since I tried various vanilla cloud-images (fed32, deb10, centos8) and non of them worked out of the box, a detailed description, what is supposed to be preinstalled, including the versions, would help.

### prerequisites:
to get the installer working, pimp the deb10 images:
```
apt-get install -y python3-dev python3-pip3
# remove version 40.8.0-1, "We expect a missing `_needs_stub` attribute from older versions of setuptools"
# during pip-install (openshift, …)
apt-get remove -y python3-setuptools
# install version 50.3
pip3 install setuptools wheel
```

### log:
```
Okt 06 11:55:37 vsn-0 kubelet[1022]: E1006 09:55:37.781945    1022 kubelet.go:1594] Unable to attach or mount volumes for pod "redis-
master-0_harbor(7b3f806f-1fba-4b9d-aacd-21b024e750ac)": unmounted volumes=[redis-data], unattached volumes=[redis-tmp-conf default-to
ken-jl49d health redis-password redis-data config]: timed out waiting for the condition; skipping pod                               
Okt 06 11:55:37 vsn-0 kubelet[1022]: E1006 09:55:37.781975    1022 pod_workers.go:191] Error syncing pod 7b3f806f-1fba-4b9d-aacd-21b0
24e750ac ("redis-master-0_harbor(7b3f806f-1fba-4b9d-aacd-21b024e750ac)"), skipping: unmounted volumes=[redis-data], unattached volume
s=[redis-tmp-conf default-token-jl49d health redis-password redis-data config]: timed out waiting for the condition                 
Okt 06 11:55:38 vsn-0 kernel: libceph: wrong peer, want 10.0.4.60:6789/0, got 10.104.98.64:6789/0                                   
Okt 06 11:55:38 vsn-0 kernel: libceph: mon1 10.0.4.60:6789 wrong peer at address                                                    
Okt 06 11:55:39 vsn-0 kernel: libceph: wrong peer, want 10.0.4.60:6789/0, got 10.104.98.64:6789/0                                   
Okt 06 11:55:39 vsn-0 kernel: libceph: mon1 10.0.4.60:6789 wrong peer at address                                                    
Okt 06 11:55:40 vsn-0 kernel: libceph: wrong peer, want 10.0.3.49:6789/0, got 10.97.11.175:6789/0                                   
Okt 06 11:55:40 vsn-0 kernel: libceph: mon2 10.0.3.49:6789 wrong peer at address                                                    
Okt 06 11:55:41 vsn-0 kernel: libceph: wrong peer, want 10.0.3.49:6789/0, got 10.97.11.175:6789/0                                   
Okt 06 11:55:41 vsn-0 kernel: libceph: mon2 10.0.3.49:6789 wrong peer at address                                                    
Okt 06 11:55:42 vsn-0 kernel: libceph: wrong peer, want 10.0.3.49:6789/0, got 10.97.11.175:6789/0                                   
Okt 06 11:55:42 vsn-0 kernel: libceph: mon2 10.0.3.49:6789 wrong peer at address                                                    
Okt 06 11:55:43 vsn-0 kernel: libceph: wrong peer, want 10.0.5.176:6789/0, got 10.104.225.94:6789/0                                 
Okt 06 11:55:43 vsn-0 kernel: libceph: mon0 10.0.5.176:6789 wrong peer at address                                                   
Okt 06 11:55:44 vsn-0 kernel: libceph: wrong peer, want 10.0.5.176:6789/0, got 10.104.225.94:6789/0                                 
Okt 06 11:55:44 vsn-0 kernel: libceph: mon0 10.0.5.176:6789 wrong peer at address                                                   
Okt 06 11:55:45 vsn-0 kernel: libceph: wrong peer, want 10.0.5.176:6789/0, got 10.104.225.94:6789/0                                 
Okt 06 11:55:45 vsn-0 kernel: libceph: mon0 10.0.5.176:6789 wrong peer at address            
```

**Comment by kisahm** [comment]
Looks like the Debian cilium problem.
Which image version you‘ve tried?

**Comment by kisahm** [comment]
Could you try the build from yesterday:
harbor.cloudical.net/vanillastack/installer:0.500.4dd79119

**Comment by chymian** [comment]
> Which image version you‘ve tried?
debian10 packer 6w old.
I now tested it with debian-10.6.0-openstack-amd64.qcow2, and that works. the culprits came from packer-prozess/iso-install. sorry for the noise.

> Could you try the build from yesterday:
> harbor.cloudical.net/vanillastack/installer:0.500.4dd79119
gives:
```
vanillastack-installer | TASK [deploy-polyverse : Upgrade all packages to the latest version] ***********      
vanillastack-installer | 
vanillastack-installer | 851503003: Sending Message
vanillastack-installer | 851503003 STDOUT: fatal: [vsm-0]: FAILED! => {"msg": "The conditional check 'polyverse.enabled' failed. The 
error was: error while evaluating conditional (polyverse.enabled): 'polyverse' is undefined\n\nThe error appears to be in '/tmp/ansib
le/roles/deploy-polyverse/tasks/main.yaml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem
.\n\nThe offending line appears to be:\n\n---\n- name: Upgrade all packages to the latest version\n  ^ here\n"}
```

**Comment by kisahm** [comment]
@chymian should be fixed by harbor.cloudical.net/vanillastack/installer:0.500.34f16271

**Comment by chymian** [comment]
@kisahm regarding the culprits with the packer-image and the wrong version of python-tools which sneaked in and had been causing trouble:
can you please define what does "bring your own Linux" include and what not? only stock images (which)? but what about installer-deployments on bare-metal? what are the exact minimum preferences (prg/vers) and HW-specs (i.e. ? x net, which network-layout, etc).

> should be fixed by harbor.cloudical.net/vanillastack/installer:0.500.34f16271

will test it and feedback

**Comment by christiancloudical** [comment]
@chymian sorry for long time of no reply.
At the end - bring your own Linux should mean what it means.
We are not focusing on cloud images, our testenvironment f.e. is build of normal kvm images ( automaticly build for sure, but no cloudcfg )
As there is a lot of options to reconsider off, we are improving the installer,step by step, to try to handle all installations at the end.
That is, as you can think of, a hard way to go ;)
But we are getting better, I hope.

Did you try, if the installation worked with image mentioned by kim?

**Comment by kisahm** [comment]
does the problem still exists?
