### ISSUE TITLE
Installation fails on Fedora 32 Server: cannot automatically set CgroupDriver when starting the Kubelet

### ISSUE THREAD

**Issue by jaybe1966** [vanillastack/vanillastack#7]
With the image
harbor.cloudical.net/vanillastack/installer                 3136726ea59a
I receive the following error:

cannot automatically set CgroupDriver when starting the Kubelet: cannot execute 'docker info -f {{.CgroupDriver}}': executable file not found in $PATH

Here is the full json sequence:
{
   "changed":true,
   "cmd":[
      "kubeadm",
      "join",
      "--token",
      "30r9ti.z32pk5efawar1in5",
      "--node-name",
      "system142",
      "--discovery-token-unsafe-skip-ca-verification",
      "--control-plane",
      "api.vanillastack.jaybe.dyndns.org:6443",
      "--certificate-key",
      "6aa8de5f9316a0adc21d2d86362465ef4ada7f3cb7c95e7a334ad6af05df21a6",
      "--apiserver-bind-port",
      "8443"
   ],
   "delta":"0:02:41.403259",
   "end":"2020-10-15 09:57:36.266842",
   "msg":"non-zero return code",
   "rc":1,
   "start":"2020-10-15 09:54:54.863583",
   "stderr":"W1015 09:55:05.805312    1127 configset.go:79] Warning: No kubeproxy.config.k8s.io/v1alpha1 config is loaded. Continuing without it: configmaps \"kube-proxy\" is forbidden: User \"system:bootstrap:30r9ti\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\"\nW1015 09:55:05.815365    1127 kubelet.go:200] cannot automatically set CgroupDriver when starting the Kubelet: cannot execute 'docker info -f {{.CgroupDriver}}': executable file not found in $PATH\nerror execution phase kubelet-start: cannot get Node \"system142\": Get \"https://api.vanillastack.jaybe.dyndns.org:6443/api/v1/nodes/system142?timeout=10s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)\nTo see the stack trace of this error execute with --v=5 or higher",
   "stderr_lines":[
      "W1015 09:55:05.805312    1127 configset.go:79] Warning: No kubeproxy.config.k8s.io/v1alpha1 config is loaded. Continuing without it: configmaps \"kube-proxy\" is forbidden: User \"system:bootstrap:30r9ti\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\"",
      "W1015 09:55:05.815365    1127 kubelet.go:200] cannot automatically set CgroupDriver when starting the Kubelet: cannot execute 'docker info -f {{.CgroupDriver}}': executable file not found in $PATH",
      "error execution phase kubelet-start: cannot get Node \"system142\": Get \"https://api.vanillastack.jaybe.dyndns.org:6443/api/v1/nodes/system142?timeout=10s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)",
      "To see the stack trace of this error execute with --v=5 or higher"
   ],
   "stdout":"[preflight] Running pre-flight checks\n[preflight] Reading configuration from the cluster...\n[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'\n[preflight] Running pre-flight checks before initializing the new control plane instance\n[preflight] Pulling images required for setting up a Kubernetes cluster\n[preflight] This might take a minute or two, depending on the speed of your internet connection\n[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'\n[download-certs] Downloading the certificates in Secret \"kubeadm-certs\" in the \"kube-system\" Namespace\n[certs] Using certificateDir folder \"/etc/kubernetes/pki\"\n[certs] Generating \"apiserver-etcd-client\" certificate and key\n[certs] Generating \"etcd/healthcheck-client\" certificate and key\n[certs] Generating \"etcd/server\" certificate and key\n[certs] etcd/server serving cert is signed for DNS names [localhost system142] and IPs [192.168.10.142 127.0.0.1 ::1]\n[certs] Generating \"etcd/peer\" certificate and key\n[certs] etcd/peer serving cert is signed for DNS names [localhost system142] and IPs [192.168.10.142 127.0.0.1 ::1]\n[certs] Generating \"apiserver\" certificate and key\n[certs] apiserver serving cert is signed for DNS names [api.vanillastack.jaybe.dyndns.org kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local system142] and IPs [10.96.0.1 192.168.10.142]\n[certs] Generating \"apiserver-kubelet-client\" certificate and key\n[certs] Generating \"front-proxy-client\" certificate and key\n[certs] Valid certificates and keys now exist in \"/etc/kubernetes/pki\"\n[certs] Using the existing \"sa\" key\n[kubeconfig] Generating kubeconfig files\n[kubeconfig] Using kubeconfig folder \"/etc/kubernetes\"\n[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address\n[kubeconfig] Writing \"admin.conf\" kubeconfig file\n[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address\n[kubeconfig] Writing \"controller-manager.conf\" kubeconfig file\n[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address\n[kubeconfig] Writing \"scheduler.conf\" kubeconfig file\n[control-plane] Using manifest folder \"/etc/kubernetes/manifests\"\n[control-plane] Creating static Pod manifest for \"kube-apiserver\"\n[control-plane] Creating static Pod manifest for \"kube-controller-manager\"\n[control-plane] Creating static Pod manifest for \"kube-scheduler\"\n[check-etcd] Checking that the etcd cluster is healthy",
   "stdout_lines":[
      "[preflight] Running pre-flight checks",
      "[preflight] Reading configuration from the cluster...",
      "[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'",
      "[preflight] Running pre-flight checks before initializing the new control plane instance",
      "[preflight] Pulling images required for setting up a Kubernetes cluster",
      "[preflight] This might take a minute or two, depending on the speed of your internet connection",
      "[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'",
      "[download-certs] Downloading the certificates in Secret \"kubeadm-certs\" in the \"kube-system\" Namespace",
      "[certs] Using certificateDir folder \"/etc/kubernetes/pki\"",
      "[certs] Generating \"apiserver-etcd-client\" certificate and key",
      "[certs] Generating \"etcd/healthcheck-client\" certificate and key",
      "[certs] Generating \"etcd/server\" certificate and key",
      "[certs] etcd/server serving cert is signed for DNS names [localhost system142] and IPs [192.168.10.142 127.0.0.1 ::1]",
      "[certs] Generating \"etcd/peer\" certificate and key",
      "[certs] etcd/peer serving cert is signed for DNS names [localhost system142] and IPs [192.168.10.142 127.0.0.1 ::1]",
      "[certs] Generating \"apiserver\" certificate and key",
      "[certs] apiserver serving cert is signed for DNS names [api.vanillastack.jaybe.dyndns.org kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local system142] and IPs [10.96.0.1 192.168.10.142]",
      "[certs] Generating \"apiserver-kubelet-client\" certificate and key",
      "[certs] Generating \"front-proxy-client\" certificate and key",
      "[certs] Valid certificates and keys now exist in \"/etc/kubernetes/pki\"",
      "[certs] Using the existing \"sa\" key",
      "[kubeconfig] Generating kubeconfig files",
      "[kubeconfig] Using kubeconfig folder \"/etc/kubernetes\"",
      "[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address",
      "[kubeconfig] Writing \"admin.conf\" kubeconfig file",
      "[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address",
      "[kubeconfig] Writing \"controller-manager.conf\" kubeconfig file",
      "[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address",
      "[kubeconfig] Writing \"scheduler.conf\" kubeconfig file",
      "[control-plane] Using manifest folder \"/etc/kubernetes/manifests\"",
      "[control-plane] Creating static Pod manifest for \"kube-apiserver\"",
      "[control-plane] Creating static Pod manifest for \"kube-controller-manager\"",
      "[control-plane] Creating static Pod manifest for \"kube-scheduler\"",
      "[check-etcd] Checking that the etcd cluster is healthy"
   ]
}

**Comment by kisahm** [comment]
could you pls verify the new image?
harbor.vanillastack.io/vanillastack/installer:0.500.d839e26f

**Comment by jaybe1966** [comment]
Also the image
harbor.vanillastack.io/vanillastack/installer:0.500.d839e26f
fails.
Logfile is attached.
[2020-10-15_01.log.txt](https://github.com/vanillastack/vanillastack/files/5387861/2020-10-15_01.log.txt)

**Comment by galexrt** [comment]
@jaybe1966 Could you ssh to the server and check if the `crio` service is running?

Post the output and file of the following commands:

```
systemctl status crio
journalctl -u crio > crio-service.log
```

**Comment by jaybe1966** [comment]
Resetted the Virtual Machines and started the installation again with image
harbor.vanillastack.io/vanillastack/installer:0.500.d839e26f
Now the installation process goes further until adding the vanillastack repository:

TASK [prepare-registry : install VanillasStack Helm repository - commercial] ***
fatal: [system141]: FAILED! => {"changed": false, "msg": "Repository already have a repository named vanillastack"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
system141                  : ok=69   changed=46   unreachable=0    failed=1    skipped=41   rescued=0    ignored=1   
system142                  : ok=59   changed=40   unreachable=0    failed=0    skipped=41   rescued=0    ignored=1   
system143                  : ok=59   changed=40   unreachable=0    failed=0    skipped=41   rescued=0    ignored=1   
system144                  : ok=47   changed=33   unreachable=0    failed=0    skipped=41   rescued=0    ignored=1   
system145                  : ok=47   changed=33   unreachable=0    failed=0    skipped=41   rescued=0    ignored=1   
system146                  : ok=47   changed=33   unreachable=0    failed=0    skipped=41   rescued=0    ignored=1   

-1
complete logfile:
[2020-10-18.log](https://github.com/vanillastack/vanillastack/files/5398117/2020-10-18.log)

**Comment by jaybe1966** [comment]
A restart of the installation leads to thiss error message:

TASK [deploy-kubernetes : install helm] ****************************************
changed: [system141]
changed: [system144]
changed: [system145]
changed: [system146]
changed: [system143]
changed: [system142]

TASK [deploy-kubernetes : remove cockpit] **************************************
fatal: [system144]: FAILED! => {"changed": false, "failures": ["cockpit* - Keine Übereinstimmung für Argumente: cockpit*"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
fatal: [system146]: FAILED! => {"changed": false, "failures": ["cockpit* - Keine Übereinstimmung für Argumente: cockpit*"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
fatal: [system145]: FAILED! => {"changed": false, "failures": ["cockpit* - Keine Übereinstimmung für Argumente: cockpit*"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
fatal: [system143]: FAILED! => {"changed": false, "failures": ["cockpit* - Keine Übereinstimmung für Argumente: cockpit*"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
fatal: [system142]: FAILED! => {"changed": false, "failures": ["cockpit* - Keine Übereinstimmung für Argumente: cockpit*"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
fatal: [system141]: FAILED! => {"changed": false, "failures": ["cockpit* - Keine Übereinstimmung für Argumente: cockpit*"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

NO MORE HOSTS LEFT *************************************************************

**Comment by jaybe1966** [comment]
I resetted the 6 VMs and restartet the installation with just 4 VMs (1 master, 3 worker) and now the installation fails with:

TASK [prepare-registry : install VanillasStack Helm repository - commercial] ***
fatal: [system142]: FAILED! => {"changed": false, "msg": "Repository already have a repository named vanillastack"}

I guess that the VM host with the VMs is just too slow to handle all the installation and configuration and it lasts too long for the required components to come up.

**Comment by jaybe1966** [comment]
Will try a newer release of the installer.
