### ISSUE TITLE
Error: etcdserver: request timed out

### ISSUE THREAD

**Issue by jaybe1966** [vanillastack/vanillastack#8]
Trying the installation of release 20.10 with installer version: Server Version 0.500.08d910d7

The Installation fails with "Error: etcdserver: request timed out"

{
   "changed":false,
   "command":"/usr/local/bin/helm --namespace=kube-system upgrade -i --reset-values --wait --create-namespace -f=/tmp/tmpor6_s7yx.yml cilium vanillastack/cilium",
   "msg":"Failure when executing Helm command. Exited 1.\nstdout: Release \"cilium\" does not exist. Installing it now.\n\nstderr: Error: etcdserver: request timed out\n",
   "stderr":"Error: etcdserver: request timed out\n",
   "stderr_lines":[
      "Error: etcdserver: request timed out"
   ],
   "stdout":"Release \"cilium\" does not exist. Installing it now.\n",
   "stdout_lines":[
      "Release \"cilium\" does not exist. Installing it now."
   ]
}

etcd server is running on every othe three master nodes:
root        3213    3196  3 10:54 ?        00:05:36 etcd --advertise-client-urls=https://192.168.10.141:2379 --cert-file=/etc/kubernetes/pki/etcd/server.crt --client-cert-auth=true --data-dir=/var/lib/etcd --initial-advertise-peer-urls=https://192.168.10.141:2380 --initial-cluster=system141=https://192.168.10.141:2380 --key-file=/etc/kubernetes/pki/etcd/server.key --listen-client-urls=https://127.0.0.1:2379,https://192.168.10.141:2379 --listen-metrics-urls=http://127.0.0.1:2381 --listen-peer-urls=https://192.168.10.141:2380 --name=system141 --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt --peer-client-cert-auth=true --peer-key-file=/etc/kubernetes/pki/etcd/peer.key --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt --snapshot-count=10000 --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt

root        2614    2575  2 10:55 ?        00:04:26 etcd --advertise-client-urls=https://192.168.10.142:2379 --cert-file=/etc/kubernetes/pki/etcd/server.crt --client-cert-auth=true --data-dir=/var/lib/etcd --initial-advertise-peer-urls=https://192.168.10.142:2380 --initial-cluster=system142=https://192.168.10.142:2380,system141=https://192.168.10.141:2380 --initial-cluster-state=existing --key-file=/etc/kubernetes/pki/etcd/server.key --listen-client-urls=https://127.0.0.1:2379,https://192.168.10.142:2379 --listen-metrics-urls=http://127.0.0.1:2381 --listen-peer-urls=https://192.168.10.142:2380 --name=system142 --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt --peer-client-cert-auth=true --peer-key-file=/etc/kubernetes/pki/etcd/peer.key --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt --snapshot-count=10000 --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt

root        2726    2685  3 10:54 ?        00:05:01 etcd --advertise-client-urls=https://192.168.10.143:2379 --cert-file=/etc/kubernetes/pki/etcd/server.crt --client-cert-auth=true --data-dir=/var/lib/etcd --initial-advertise-peer-urls=https://192.168.10.143:2380 --initial-cluster=system142=https://192.168.10.142:2380,system143=https://192.168.10.143:2380,system141=https://192.168.10.141:2380 --initial-cluster-state=existing --key-file=/etc/kubernetes/pki/etcd/server.key --listen-client-urls=https://127.0.0.1:2379,https://192.168.10.143:2379 --listen-metrics-urls=http://127.0.0.1:2381 --listen-peer-urls=https://192.168.10.143:2380 --name=system143 --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt --peer-client-cert-auth=true --peer-key-file=/etc/kubernetes/pki/etcd/peer.key --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt --snapshot-count=10000 --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt

[2020-10-24.log](https://github.com/vanillastack/vanillastack/files/5432800/2020-10-24.log)

**Comment by jaybe1966** [comment]
The used systems are just too slow for handling the requests.
Switching to other systems and trying again.

**Comment by toxynoid** [comment]
Was this issue really solved by switching system?

**Comment by jaybe1966** [comment]
I tried to install vanillastack on six VMs, running on on a host with a single CPU and just 32GB RAM.
The minimal required configuration should be fulfilled, bu it takes very, very long to start up the six vms and to reboot them during the installation. Waiting for the nodes to start the pods takes too long and times out.
I will now use four separate older PCs, each will run a single VM.
I will use the VMs just to take snapshots to be able to reset and try again without having to newly setup four physical machines.
I hope that this new setup is able to handle the load of installing vanillastack.

**Comment by toxynoid** [comment]
I do have this issue with 12 cores with HT enabled and 142 GB RAM. I don't want to believe this issue is a lack of resources.

**Comment by jaybe1966** [comment]
My actual config:
- Four VM-Hosts, each of them running one VM with one node.
- The four CPUs of the host systems:
Xeon(R) CPU E3-1225 V2 @ 3.20GHz
Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
- each node is configured with 4GB RAM an 2 CPU

With vanillastack 20.10, image version 0.500.08d910d7, I was now able to install vanillastack.
Configuration options:
rook dashboard: enabled
harbor: disabled
prometheus: disabled
grafana: disabled

I haven't tried to work with it yet but this was the first time, the installation process completed without any errors.
[2020-10-27_success.log](https://github.com/vanillastack/vanillastack/files/5444240/2020-10-27_success.log)

**Comment by jaybe1966** [comment]
Installed it two times with success:

kubectl cluster-info
Kubernetes master is running at https://192.168.10.141:8443
KubeDNS is running at https://192.168.10.141:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
kubernetes-dashboard is running at https://192.168.10.141:8443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:https/proxy

kubectl get nodes
NAME        STATUS   ROLES    AGE   VERSION
system141   Ready    master   99m   v1.19.3
system144   Ready    worker   98m   v1.19.3
system145   Ready    worker   98m   v1.19.3
system146   Ready    worker   98m   v1.19.3

kubectl get ns
NAME                STATUS   AGE
cert-manager        Active   88m
default             Active   99m
kube-node-lease     Active   99m
kube-public         Active   99m
kube-system         Active   99m
kubevirt            Active   87m
moodle              Active   87m
nginx-ingress       Active   96m
postgres-operator   Active   87m
rook-ceph           Active   95m


# Get PODs for namespace cert-manager
NAME                                      READY   STATUS    RESTARTS   AGE
cert-manager-cainjector-fc6c787db-7jqlr   1/1     Running   0          88m
cert-manager-d994d94d7-7jfzn              1/1     Running   0          88m
cert-manager-webhook-845d9df8bf-8hjc7     1/1     Running   0          88m
# Get PODs for namespace default
No resources found in default namespace.
# Get PODs for namespace kube-node-lease
No resources found in kube-node-lease namespace.
# Get PODs for namespace kube-public
No resources found in kube-public namespace.
# Get PODs for namespace kube-system
NAME                                    READY   STATUS    RESTARTS   AGE
cilium-5mcrd                            1/1     Running   0          98m
cilium-operator-5dccb574f9-rj76d        1/1     Running   0          98m
cilium-operator-5dccb574f9-stzk5        1/1     Running   0          98m
cilium-pfvzh                            1/1     Running   0          98m
cilium-qrnxz                            1/1     Running   0          98m
cilium-rf5vw                            1/1     Running   0          98m
cm-acme-http-solver-2hxrb               1/1     Running   0          88m
coredns-f9fd979d6-l7srs                 1/1     Running   0          97m
coredns-f9fd979d6-pfm9b                 1/1     Running   0          97m
etcd-system141                          1/1     Running   0          99m
hubble-relay-659f8c8f87-ltsd6           1/1     Running   0          98m
hubble-ui-7854cf65dc-g7rxc              1/1     Running   0          98m
kube-apiserver-system141                1/1     Running   0          99m
kube-controller-manager-system141       1/1     Running   0          99m
kube-scheduler-system141                1/1     Running   0          99m
kubernetes-dashboard-656cc6d646-44fw4   1/1     Running   0          88m
# Get PODs for namespace kubevirt
NAME                             READY   STATUS    RESTARTS   AGE
virt-operator-7c8fbb654c-l58qx   1/1     Running   0          87m
virt-operator-7c8fbb654c-lvhf5   1/1     Running   0          87m
# Get PODs for namespace moodle
NAME                      READY   STATUS                       RESTARTS   AGE
mariadb-moodle-0          2/2     Running                      0          87m
moodle-67fd5cfc54-znw24   1/2     CreateContainerConfigError   0          87m
# Get PODs for namespace nginx-ingress
NAME                                            READY   STATUS    RESTARTS   AGE
nginx-ingress-controller-57bf66fcd8-448r2       1/1     Running   0          97m
nginx-ingress-controller-57bf66fcd8-6shcg       1/1     Running   0          97m
nginx-ingress-controller-57bf66fcd8-b4czv       1/1     Running   0          97m
nginx-ingress-default-backend-c5449fb44-hjpfp   1/1     Running   0          97m
# Get PODs for namespace postgres-operator
NAME                                 READY   STATUS    RESTARTS   AGE
postgres-operator-5f98ffbb7c-c7rlh   1/1     Running   0          88m
# Get PODs for namespace rook-ceph
NAME                                                  READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-86fkh                                3/3     Running     0          94m
csi-cephfsplugin-96w8v                                3/3     Running     0          94m
csi-cephfsplugin-k686p                                3/3     Running     0          94m
csi-cephfsplugin-provisioner-6664464f8c-ckmb8         6/6     Running     0          94m
csi-cephfsplugin-provisioner-6664464f8c-h8m7r         6/6     Running     0          94m
csi-rbdplugin-l69gw                                   3/3     Running     0          94m
csi-rbdplugin-p2rmg                                   3/3     Running     0          94m
csi-rbdplugin-provisioner-557845dbc-7kppf             6/6     Running     0          94m
csi-rbdplugin-provisioner-557845dbc-r54nb             6/6     Running     0          94m
csi-rbdplugin-swlh9                                   3/3     Running     0          94m
rook-ceph-crashcollector-system144-856b647c75-mc58g   1/1     Running     0          92m
rook-ceph-crashcollector-system145-85f4dcd956-7vhf7   1/1     Running     0          92m
rook-ceph-crashcollector-system146-888866bf-rn5kt     1/1     Running     0          90m
rook-ceph-mgr-a-6bbdcb4bd8-m2c8z                      1/1     Running     0          91m
rook-ceph-mon-a-78966f98bd-7zp6j                      1/1     Running     0          93m
rook-ceph-mon-b-cccc64d88-dvqk2                       1/1     Running     0          92m
rook-ceph-mon-c-7798db645c-tfwmw                      1/1     Running     0          92m
rook-ceph-operator-5f5fd8bf77-zsx2m                   1/1     Running     0          96m
rook-ceph-osd-0-78c4689589-h2ml9                      1/1     Running     0          90m
rook-ceph-osd-1-c7df4cb67-kd4nb                       1/1     Running     0          90m
rook-ceph-osd-2-786f74949d-dxrz6                      1/1     Running     0          90m
rook-ceph-osd-prepare-system144-s2864                 0/1     Completed   0          33m
rook-ceph-osd-prepare-system145-tvtn7                 0/1     Completed   0          33m
rook-ceph-osd-prepare-system146-86c7t                 0/1     Completed   0          33m
rook-ceph-tools-649c4dd574-hjw4t                      1/1     Running     0          90m
rook-discover-94p7m                                   1/1     Running     0          95m
rook-discover-94snb                                   1/1     Running     0          95m
rook-discover-bq2r8                                   1/1     Running     0          95m

**Comment by toxynoid** [comment]
I made an successful install without high availability as well. I'll try an install with HA when my SSDs arrive.

**Comment by kisahm** [comment]
@toxynoid does the ssds fixed the problem?

**Comment by toxynoid** [comment]
Kind of yes. I have ssds and kubernetes installed, but with kubespray.

Am Sa., 9. Jan. 2021 um 15:39 Uhr schrieb Kim-Norman Sahm <
notifications@github.com>:
